authn/urls.py
from django.contrib import admin 
from django.urls import path
from . import views
app_name='authn'
urlpatterns=[
    path('',views.index,name='index'),
    path('login/',views.userlogin,name='userlogin'),
    path('signup/',views.usersignup,name='usersignup'),
    path('signup/create_user/',views.create_user,name='create_user'),
    path('feature/logout/',views.logoutUser,name='logoutUser')

]

contact/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("feature.urls",namespace='features')),
    path('',include("authn.urls",namespace='authns')),
    
    
]

feature/urls.py
from django.contrib import admin
from django.urls import path,include
from feature import views 
app_name="feature"
urlpatterns = [
    path('feature/',views.index,name="index"),
    path('add/',views.add,name="add"),
    path('feature/delete/<int:phone>',views.delete,name="delete"),
]

authn/models.py
# from django.db import models

# # Create your models here.

# from django.contrib.auth.models import AbstractUser
# from django.db import models

# class CustomUser(AbstractUser):
#     # Add your custom fields here
#     phone=models.BigIntegerField(default=0,blank=False)
#     def __str__(self):
#         return self.username

feature/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Contact(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE,default="")
    name=models.CharField(max_length=30)
    email=models.EmailField()
    phone=models.BigIntegerField(primary_key=True)

    def __str__(self):
        return self.name

authn/views.py
from django.shortcuts import render,redirect,HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import logout,authenticate,login
from django.shortcuts import get_object_or_404
# Create your views here.
# views.py
# from django.contrib.auth import get_user_model

# User = get_user_model()

def index(request):
    if request.user.is_anonymous:
        return render(request,'authn/login.html')
    return redirect('feature:index')

def usersignup(request):
    return render(request,'authn/signup.html')


def create_user(request):
    if(request.method=='POST'):
        username=request.POST['username']
        password=request.POST['password']
        try:
            check=get_object_or_404(User,username=username)
        except:
            try:
                user=User.objects.create_user(username=username,password=password)
                user.save()
            except:
                print("not created")
            return redirect('authn:index')
    
    return redirect('authn:index')
    





def userlogin(request):

    if request.method=="POST":
        username=request.POST['username']
        password=request.POST['password']
        user=authenticate(username=username,password=password)
        print(username,password)
        if user is not None:
            login(request,user)
            
        
            return redirect('authns:index')
    
    return redirect('authn:index')


def logoutUser(request):
    logout(request)
    return redirect('authn:index')

feature/views.py
from django.shortcuts import render,HttpResponseRedirect,redirect,reverse,HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import logout,authenticate,login
# Create your views here.
from .models import Contact


def index(request):
    if request.user.is_anonymous:
        return redirect('authn:index')
    # print(User)
    contacts=Contact.objects.filter(user=request.user)
    parms={"contacts":contacts}
    return render(request,'feature/index.html',parms)

def add(request):
    name=request.POST['name']
    email=request.POST['email']
    phone=request.POST['phone']
    try:
        print('added')
        contact=Contact.objects.create(user=request.user,name=name,email=email,phone=phone)
        contact.save()
    except :
        print("not added")
        return redirect('features:index')
    return redirect('features:index')

def delete(request,phone):
    Contact.objects.filter(phone=phone).delete()
    return redirect("features:index")

authn/templates/authn/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>



  <h1> authn index page </h1>

    <form action="logout/" >
        {% csrf_token %}
      <button type="submit" class="btn btn-primary btn-block mb-4">logout</button>

    </form>



    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

authn/templates/authn/login.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
<!-- Section: Design Block -->
{% comment %} <section class=" text-center text-lg-start">
  <style>
    .rounded-t-5 {
      border-top-left-radius: 0.5rem;
      border-top-right-radius: 0.5rem;
    }

    @media (min-width: 992px) {
      .rounded-tr-lg-0 {
        border-top-right-radius: 0;
      }

      .rounded-bl-lg-5 {
        border-bottom-left-radius: 0.5rem;
      }
    }
  </style>
  <div class="card mb-3">
    <div class="row g-0 d-flex align-items-center">
      <div class="col-lg-4 d-none d-lg-flex">
        <img src="https://mdbootstrap.com/img/new/ecommerce/vertical/004.jpg" alt="Trendy Pants and Shoes"
          class="w-100 rounded-t-5 rounded-tr-lg-0 rounded-bl-lg-5" />
      </div>
      <div class="col-lg-8">
        <div class="card-body py-5 px-md-5">

          <form action="login/" method="post">
            {% csrf_token %}
            <!-- Email input -->
            <div class="form-outline mb-4">
              <input type="text" id="username" name="username" class="form-control" />
              <label class="form-label" for="username">Username</label>
            </div>

            <!-- Password input -->
            <div class="form-outline mb-4">
              <input type="password" id="password" name="password" class="form-control" />
              <label class="form-label" for="password">Password</label>
            </div>

            <!-- 2 column grid layout for inline styling -->


            <!-- Submit button -->
            <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>

          </form>

        </div>
      </div>
    </div>
  </div>
</section>   {% endcomment %}
<!-- Section: Design Block -->

<section class="vh-100" style="background-color: #508bfc;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-2-strong" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">

           
          <form action="login/" method="post">
            {% csrf_token %}
             <h3 class="mb-5">Sign in</h3>
            <!-- Email input -->
            <div class="form-outline mb-4">
              <input type="text" id="username" name="username" class="form-control" placeholder="Username"/>
              {% comment %} <label class="form-label" for="username">Username</label> {% endcomment %}
            </div>

            <!-- Password input -->
            <div class="form-outline mb-4">
              <input type="password" id="password" name="password" class="form-control" placeholder="Password" />
              {% comment %} <label class="form-label" for="password">Password</label> {% endcomment %}
            </div>

            <!-- 2 column grid layout for inline styling -->


            <!-- Submit button -->
            <div class="flex-row">
              <button type="submit" class="btn btn-primary">Sign in</button>
              
              <a href="signup"><button type="button" class="btn btn-primary">Sign up</button></a>
            </div>

          </form>
         

          </div>
        </div>
      </div>
    </div>
  </div>
</section> 




    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

authn/templates/authn/signup.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
<!-- Section: Design Block -->
{% comment %} <section class=" text-center text-lg-start">
  <style>
    .rounded-t-5 {
      border-top-left-radius: 0.5rem;
      border-top-right-radius: 0.5rem;
    }

    @media (min-width: 992px) {
      .rounded-tr-lg-0 {
        border-top-right-radius: 0;
      }

      .rounded-bl-lg-5 {
        border-bottom-left-radius: 0.5rem;
      }
    }
  </style>
  <div class="card mb-3">
    <div class="row g-0 d-flex align-items-center">
      <div class="col-lg-4 d-none d-lg-flex">
        <img src="https://mdbootstrap.com/img/new/ecommerce/vertical/004.jpg" alt="Trendy Pants and Shoes"
          class="w-100 rounded-t-5 rounded-tr-lg-0 rounded-bl-lg-5" />
      </div>
      <div class="col-lg-8">
        <div class="card-body py-5 px-md-5">

          <form action="login/" method="post">
            {% csrf_token %}
            <!-- Email input -->
            <div class="form-outline mb-4">
              <input type="text" id="username" name="username" class="form-control" />
              <label class="form-label" for="username">Username</label>
            </div>

            <!-- Password input -->
            <div class="form-outline mb-4">
              <input type="password" id="password" name="password" class="form-control" />
              <label class="form-label" for="password">Password</label>
            </div>

            <!-- 2 column grid layout for inline styling -->


            <!-- Submit button -->
            <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>

          </form>

        </div>
      </div>
    </div>
  </div>
</section>   {% endcomment %}
<!-- Section: Design Block -->

<section class="vh-100" style="background-color: #508bfc;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-2-strong" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">

           
          <form action="create_user/" method="post">
            {% csrf_token %}
             <h3 class="mb-5">Sign up</h3>
            <!-- Email input -->
            <div class="form-outline mb-4">
              <input type="text" id="username" name="username" class="form-control" placeholder="Username" />
              {% comment %} <label class="form-label" for="username">Username</label> {% endcomment %}
            </div>
            {% comment %} <div class="form-outline mb-4">
              <input type="number" id="phone" name="phone" class="form-control" />
              <label class="form-label" for="phone">Username</label>
            </div> {% endcomment %}
            <!-- Password input -->
            <div class="form-outline mb-4">
              <input type="password" id="password" name="password" class="form-control" placeholder="Password" />
              {% comment %} <label class="form-label" for="password">Password</label> {% endcomment %}
            </div>

            <!-- 2 column grid layout for inline styling -->


            <!-- Submit button -->
            <button type="submit" class="btn btn-primary">Sign up</button>

          </form>
         

          </div>
        </div>
      </div>
    </div>
  </div>
</section> 




    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

feature/templates/feature/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    <div class="container px-5">
        <div class="sticky-top">
            <nav class="navbar bg-dark border-bottom border-body px-2 mt-2">
            <div class="container-fluid">
                {% comment %} <a class="navbar-brand">Navbar</a> {% endcomment %}
                <form class="d-flex" role="search">
                    {% csrf_token %}
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                
                </form>
                <form class="form-inline" action='logout/'>
                    {% csrf_token %}
                    <button class="btn btn-outline-success" type="submit">log out</button>
                    
                </form>
            </div>
            </nav>
            <div class="card col-md-12 py-2 my-2">
                    <form action="{%url 'features:add' %}" method='POST'>
                        {% csrf_token %}
                        <div class="form-group px-2 py-2">
                            {% comment %} <label for="name">Name</label> {% endcomment %}
                            <input type="text" class="form-control" name="name" id="name" placeholder="Enter Full Name">
                        </div>
                        <div class="form-group  px-2 py-2">
                            {% comment %} <label for="email">Email</label> {% endcomment %}
                            <input type="email" class="form-control" id="email" name="email"aria-describedby="emailHelp" placeholder="Enter Email">
                            {% comment %} <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> {% endcomment %}
                        </div>
                        <div class="form-group  px-2 py-2">
                            {% comment %} <label for="">Phone</label> {% endcomment %}
                            <input type="number" class="form-control"  name="phone"id="phone" placeholder="Enter Phone">
                        </div>
                        <div class=" px-2 py-2">
                        <button type="submit" class="btn btn-primary">Add</button>
                        </div>
                    </form> 

            </div>     
        </div>
        
        <div>
                {%for contact in contacts %}
                  <div class="card flex-row my-2" >
                   
                        <div class="card col-md-3 px-2 py-2 mx-4 my-4 center">
                            {{contact.name}}
                        </div>
                        <div class="card col-md-3 px-2 py-2  mx-4 my-4 center">
                            {{contact.phone}}
                        </div>
                        <div class="card col-md-3 px-2 py-2  mx-4 my-4 center">
                            {{contact.email}}
                        </div>

                        <div class="px-2 py-2  mx-4 my-4">
                    
                            <form method="POST" action="delete/{{contact.phone}}">
                                {% csrf_token %}
                                {% comment %} <button type="submit" name="action" value="some_action">Perform Action</button> {% endcomment %}
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                        </div>
                    
                  </div>
                {%endfor%}

        </div>
        
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>